---
version: "3.9"

services:
  qbit:
    build: .
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    container_name: qbit-vpn
    restart: unless-stopped
    ports:
      - 80:80
      - 6881:6881
      - 6881:6881/udp
    env_file:
      - .env
    volumes:
      - /config:/config
      - /downloads:/downloads
